name: ⭐ Feature request
description: Create a detailed feature request.
title: 'feat: <title>'
labels: [feature-request]
body:
  - type: dropdown
    attributes:
      label: Type
      options:
        - Functionality
        - Cosmetic
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Branch
      description: Which github branch did you use (Flutter or Compose)?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue
      description: What is the current problem. Why does it require a feature request?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feature
      description: Describe your feature in detail. How does it solve the issue?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Why should your feature should be considered?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context here.
    validations:
      required: false